### ISSUE TITLE
Downloading RSEM exon data

### ISSUE THREAD

**Issue by agustin-guardiola** [wenjie1991/TSVdb#26]
When downloading the data from TSVdb, what are the units of the exon usage value, and how can I get RSEM values from those?

Thanks

**Comment by wenjie1991** [comment]
Hi,

> When downloading the data from TSVdb, what are the units of the exon usage value

First, answer your question directly: The units of downloaded exon data are **RPKM** values (Reads Per Kilobase of exon model per Million mapped reads).

The data that you downloaded from the "Download Data" is the original data. That means it is as it is from the TCGA firehose database, as well as the gene and isoform expression data. I am sorry for the misleading document and phrase in the paper. I will try to fix it.

The "exon" quantification data were [downloaded from Firehose](https://github.com/wenjie1991/TSVdb/blob/cb0895a82f421596032ae12b954d0b557158a4bf/prepare_database/download_from_firehose.pl6#L10), then stored in MongoDB after [formating by an `R` script](https://github.com/wenjie1991/TSVdb/blob/cb0895a82f421596032ae12b954d0b557158a4bf/prepare_database/mongodb_json_prepare_all.R#L109), and [formatted by a server script when you download it](https://github.com/wenjie1991/TSVdb/blob/cb0895a82f421596032ae12b954d0b557158a4bf/server_nodejs/downloadData.js#L85). 


> how can I get RSEM values from those

I think you can use RPKM instead of RSEM. Also, there is no exon or junction RSEM quantification.

Let me know if you have any other questions.

Best,
Wenjie

**Comment by agustin-guardiola** [comment]
Thank you, a paper I was following mentioned downloading exon RSEM with this tool and the numbers didn't match the ones I downloaded, I might contact them about it.
Thanks!
