### ISSUE TITLE
PRAD database exon and junction positions

### ISSUE THREAD

**Issue by agustin-guardiola** [wenjie1991/TSVdb#27]
Hey, 
I'm looking at the PRAD database and when I download the exon and junction data for the LCK gene the start and end positions of the exons and junctions don't make sense to me.
I would expect a junction to start where the previous exon ends, and to end where the next exon starts, but when I plot start and end positions this is what I get:
![image](https://user-images.githubusercontent.com/57628802/70525855-2886c800-1b40-11ea-9ec0-cbe15493290b.png)
exons are the blue segments, start and end marked with a dot.
junctions are the red segments, start and end marked with a cross.
Look at junction 2 and junction 4 for example. They appear to be fully contained within exons 2 and 3 respectively. Is this to be expected? Would this be an issue with the original TCGA database?

Thanks!

**Comment by wenjie1991** [comment]
Hello,

The overlapping of junctions means there can be alternative splicing.
In your demonstration: the exon7 (e7) can be skipped, so there is a possible junction (let us call it Je5-e7), which jumps over the exon7 and links e5 and e7. The junction Je5-e7 is overlap with the junction, which connects e5 & e6 and junction, which links e6 & e7.

> Look at junction 2 and junction 4 for example. They appear to be fully contained within exons 2 and 3 respectively.

I guess the e3 can be split into two exons. But the next-generation sequencing good at identifying the junction events rather than identifying exon. So the junction of the potential alternative splicing was identified but not the exon.

My suggestion is to interpret the result in the biological context. Because of the existence of such complexity, we need to interpret the junction information with the transcription pattern. You can use the information in the UCSC Genome Browser. By using the TSVdb, you can **double click** the junction or exon area to open a UCSC Genome Browser with a specific junction or exon highlighted.

![2019-12-10 16-02-48 2019-12-10 16_04_57](https://user-images.githubusercontent.com/6602710/70541329-1c623100-1b67-11ea-82de-376856bcb65c.gif)

**Comment by agustin-guardiola** [comment]
I think that makes sense! 

Thank you very much
